import logging
import secrets
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.asymmetric import x25519
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.kdf.hkdf import HKDF

logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")

# --- Key generation ---
# Alice is the initiator, Bob is the responder. Roles are tracked explicitly
# below so the derived key is bound to who-did-what, not just to an
# unordered pair of keys.
alice_private = x25519.X25519PrivateKey.generate()
alice_public = alice_private.public_key()
logging.info("Alice's key pair generated.")

bob_private = x25519.X25519PrivateKey.generate()
bob_public = bob_private.public_key()
logging.info("Bob's key pair generated.")

# --- ECDH exchange ---
# NOTE: This is the crux of why raw ECDH is not enough on its own.
# alice_public / bob_public are exchanged here with no signature, certificate,
# or prior-known fingerprint check. In a real network, an attacker could
# substitute their own key for either party's and neither side would notice
# (a classic Alice <-> Mallory <-> Bob man-in-the-middle). A real protocol
# would sign these keys with a long-term identity key, or verify them
# against a certificate/PKI, before ever using them.
alice_shared_secret = alice_private.exchange(bob_public)
bob_shared_secret = bob_private.exchange(alice_public)
logging.info("Shared secrets computed.")


def public_bytes(key: x25519.X25519PublicKey) -> bytes:
    return key.public_bytes(
        encoding=serialization.Encoding.Raw,
        format=serialization.PublicFormat.Raw,
    )


def derive_key_hkdf(
    shared_secret: bytes,
    initiator_pub: bytes,
    responder_pub: bytes,
    salt: bytes,
    length: int = 32,
) -> bytes:
    """
    Derive a symmetric key from a shared ECDH secret using HKDF-SHA256.

    `info` explicitly encodes initiator/responder roles rather than just
    sorting the two public keys.

    `salt` should be a fresh random value agreed by both parties.
    """
    logging.info("Deriving key using HKDF.")

    info = b"ecdh key|initiator=" + initiator_pub + b"|responder=" + responder_pub

    return HKDF(
        algorithm=hashes.SHA256(),
        length=length,
        salt=salt,
        info=info,
    ).derive(shared_secret)


alice_pub_bytes = public_bytes(alice_public)
bob_pub_bytes = public_bytes(bob_public)

# Random per-session salt, per RFC 5869's recommendation over an empty salt.
# In a real handshake this would be generated by one party (or derived from
# a nonce exchange) and transmitted to the other -- both sides must use the
# identical value, or their derived keys won't match.
shared_salt = secrets.token_bytes(32)

alice_key = derive_key_hkdf(alice_shared_secret, alice_pub_bytes, bob_pub_bytes, shared_salt)
bob_key = derive_key_hkdf(bob_shared_secret, alice_pub_bytes, bob_pub_bytes, shared_salt)
logging.info("Keys derived for both Alice and Bob.")

print("Alice's derived key (SHA-256):", alice_key.hex())
print("Bob's derived key   (SHA-256):", bob_key.hex())

# NOTE: This assertion only "works" because both parties' keys exist in this
# single process. In reality Alice and Bob are on separate machines, and
# neither can see the other's derived key directly. Proving both sides
# derived the same key requires an explicit key confirmation step -- e.g.
# each side computes and sends HMAC(derived_key, b"confirm") and the other
# verifies it matches -- never compare or transmit the raw derived key
# itself.
try:
    assert alice_key == bob_key, "ERROR: Alice and Bob keys do not match!"
    logging.info("SUCCESS: Shared key established successfully! (Still no authentication or key confirmation, though.)")
except AssertionError as e:
    logging.error(e)